### ISSUE TITLE
No Response 

### ISSUE THREAD

**Issue by Bleez103** [Asteezy24/SupremeRestocks#3]
Currently getting an no response when running the supreme.js. I ran it with and without proxies loaded and it came back with the same message.

![image](https://user-images.githubusercontent.com/25425376/33621511-d200ebb6-d99f-11e7-8240-2e0442fadcf0.png)

**Comment by Asteezy24** [comment]
I fixed the twitter and version issue, and when I do a fresh git clone into a new directory the monitor runs fine for me. Could you try again with the new version and let me know if the same thing happens?

**Comment by Bleez103** [comment]
@Asteezy24  I  cloned into a new directory and am still getting the "Did not get response" message. I ran the supreme.js with and without proxies loaded. The bot joins the slack channel and I've uncommented all of the necessary lines.

![image](https://user-images.githubusercontent.com/25425376/33675079-47035fa4-da66-11e7-954d-a2db2de7ca48.png)


** EDIT **

I adjusted the timeout value to 40000 (Line 73) to an pretty high value. I'm now am not getting the "Did not get response" message. Also, ran the same value with proxies loaded and it gives the "Did not get response" message

![image](https://user-images.githubusercontent.com/25425376/33679408-8a33ac72-da73-11e7-8016-b8b1fe9f6743.png)

![image](https://user-images.githubusercontent.com/25425376/33679380-761de126-da73-11e7-93d0-206de78ae3b8.png)
